language: ruby

before_install:
  - mkdir -p tmp/cache

services:
  - redis-server

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=pre"